### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by morrigan** [ethereum-ts/truffle-typings#12]
Hi,

do you have an example app with this? Migrations doesn't seem to run for this repo [https://github.com/NodeFactoryIo/solidity-docker-starter](https://github.com/NodeFactoryIo/solidity-docker-starter).

**Comment by krzkaczor** [comment]
Hey 👋 

Example is here: https://github.com/ethereum-ts/truffle-typechain-example

If you have any other problems please reopen.
