### ISSUE TITLE
Missing typings

### ISSUE THREAD

**Issue by sneko** [ethereum-ts/truffle-typings#4]
Hi @krzkaczor 😃 

I was just trying Truffle example (MetaCoin) and I noticed there is an issue with typings: 
`[ts] Property 'link' does not exist on type 'Deployer'`

Line of code:
`deployer.link(ConvertLib, MetaCoin);`

Thank you for your work 🎆

**Comment by krzkaczor** [comment]
Released as: `+ truffle-typings@1.0.5`. Sorry for the delay, devcon stuff 😆
