### ISSUE TITLE
Package is out of sync with NPM

### ISSUE THREAD

**Issue by hickscorp** [ethereum-ts/truffle-typings#9]
When installing `truffle-typings` using yarn or NPM, the latest tag from NPM is installed `1.0.6`.

However, there is no such tag / version here on the github repository, and the `index.d.ts` is obviously out of sync (Missing the latest commits).

I would suggest tagging / bumping clean and pushing to NPM, as some issues raised in other repositories would greatly benefit from the most recent commits to `truffle-typings`.

A temporary solution is indeed to reference the package like this: `"truffle-typings": "git+https://github.com/ethereum-ts/truffle-typings.git#master",` from `package.json` but it's not very intuitive.

**Comment by krzkaczor** [comment]
I just published new version @hickscorp thanks for this issue. Regarding your PR, I am not sure if `default` change is needed. 🤷‍♂

**Comment by hickscorp** [comment]
@krzkaczor Thanks a lot for the reactivity, I'm sorry for the double-issue in that case. Shall we close this PR then?

**Comment by krzkaczor** [comment]
Yeah, lets close it. Just let me know please if the freshly released package works for you :)
